### ISSUE TITLE
中继功能好像不能正常使用

### ISSUE THREAD

**Issue by chenall** [danbai225/go-rustdesk-server#5]
日志有错误提示 [ERR]:  monitor.go:143 invalid argument to Intn

![image](https://user-images.githubusercontent.com/628011/177444187-a4b86242-abc3-4e2d-8847-1af708170064.png)

端口都有正常开放,使用官方的 hbbs 和 hbbr 使用正常.

配置是默认的配置
```
{
  "whiteList": false,
  "ipList": [
    "127.0.0.1"
  ],
  "debug": true,
  "reg_server":"127.0.0.1:21120",
  "relay_name":"go_rust_desk_relay",
  "server_port": 21116,
  "relay_port":21117,
  "reg_port": 21120
}
```

**Comment by danbai225** [comment]
请问是用的docker嘛

**Comment by chenall** [comment]
我是 windows 的环境,直接下载源码编译的

go build --ldflags "-w -s"

**Comment by danbai225** [comment]
我刚才改了下疑似中继服务器没有连上。你再拉下代码编译一下试试。看看有没有注册成功的提示

**Comment by chenall** [comment]
试了有注册成功的提示信息还是不行
```
2022-07-06 13:41:42        [ERR]:  speedtest.go:33 socket: The requested protocol has not been configured into the system, or no implementation for it exists.
2022-07-06 13:41:44        [INFO]: relay.go:144 注册成功[39m
```

**Comment by chenall** [comment]
调试了一下太概可能找到原因了

https://github.com/danbai225/go-rustdesk-server/blob/dd5149365e0b99606e7025ab25edadb360628e53/server/sync.go#L58

同一台机器上获取到的 IP 是 127.0.0.1,需要转成公网 IP .

这边能不能改成中继服务器注册时指定要使用的 IP  地址?

另外这边

https://github.com/danbai225/go-rustdesk-server/blob/dd5149365e0b99606e7025ab25edadb360628e53/relay/relay.go#L141

直接退出程序?

**Comment by danbai225** [comment]
这个地址是发起注册时的连接ip，我没法知道远端的公网ip，这样的话建议在填写配置的时候，填写注册服务器的公网地址。
后面我改下这，改成中继服务器获取了公网地址在注册时携带。

退出这个是因为注册已经失败了，就无意义运行了

**Comment by chenall** [comment]
> 这个地址是发起注册时的连接ip，我没法知道远端的公网ip，这样的话建议在填写配置的时候，填写注册服务器的公网地址。 后面我改下这，改成中继服务器获取了公网地址在注册时携带。
> 
> 退出这个是因为注册已经失败了，就无意义运行了

因为我刚才测试时直接把 writer.GetAddr().GetIP(), 改成了我服务器的公网 IP ,导致运行的时候到后面直接自动退出了^_^
因为下面的判断 "existName ".

**Comment by chenall** [comment]
另外一个小问题,那个中继测速的好像 windows 不支持.

**Comment by danbai225** [comment]
对我看到了，到时看看有没有什么兼容办法。
这个影响不大，我最近使用连接上有时候连不上需要多连几次，这个问题比较严重。
我回头装个官方的体验下，看下是服务器网络问题还是程序哪里有bug
