### ISSUE TITLE
armv7有没有docker镜像呢?

### ISSUE THREAD

**Issue by winsel** [danbai225/go-rustdesk-server#8]
自己编译通不过,不会golang,要是这个能继续更新就好了,官方免费的用一段时间不知道什么情况就连不上了,得删除镜像重新安装,免费版的什么管理功能也没有,收费的又太贵

**Comment by danbai225** [comment]
很感谢您的使用，目前没有编译armv7的镜像。我看看后面我加上，然后更新的话我后面有时间。跟上，我不知道还有人在用。2023年11月22日 11:14，winsel ***@***.***>写道：
自己编译通不过,不会golang,要是这个能继续更新就好了,官方免费的用一段时间不知道什么情况就连不上了,得删除镜像重新安装,免费版的什么管理功能也没有,收费的又太贵
